services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  browser:
    build: ./browser
    ports:
      - "3001:3001"
      - "6180-6190:6180-6190"

  postgres:
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
