services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - BROWSER_PUBLIC_URL=http://localhost:3001

  browser:
    build: ./browser
    ports:
      - "3001:3001"

  extractor:
    build: ./backend
    ports:
      - "3002:3001"

  postgres:
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
